name: Docker configuration validations

on:
  push:
    branches-ignore: [master, develop]

jobs:
  run-linters:
   name: Run lint on docker files
   runs-on: ubuntu-latest

   steps:
    - name: Checkout git repository
      uses: actions/checkout@v4
      
    - name: Lint Dockerfile
      uses: docker/lint-action@v1.0.0
      with:
       dockerfile: ./Dockerfile

    - name: Lint Docker Compose
      run: docker compose -f docker-compose.yaml config -q
