name: Restrict PRs to Main

on:
  pull_request:
    branches:
      - master

jobs:
  restrict-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR target branch
        run: |
          echo "Checking the target branch of the PR..."
          if [[ "${{ github.event.pull_request.base.ref }}" == "master" ]]; then
            echo "PRs to the 'main' branch are restricted. Please make PRs to the 'develop' branch."
            exit 1
          else
            echo "PR target branch is not 'master'. Proceeding..."
          fi
