name: Restrict PRs to Master

on:
  pull_request:
    branches:
      - master

jobs:
  restrict-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR target branch
        run: |
          echo "Checking the target branch of the PR..."
          if [[ "${{ github.event.pull_request.head.ref }}" != "develop" ]]; then
            echo "PRs to the 'master' branch are restricted. Please make PRs to the 'develop' branch."
            exit 1
