name: Restrict PRs to Master

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  restrict-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR target branch
        run: |
          echo "Checking the target branch of the PR..."
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH=${{ github.event.pull_request.head.ref }}

          if [ "$BASE_BRANCH" == "master" ] && [ "$HEAD_BRANCH" != "develop" ]; then
            echo "PRs to the 'master' branch are restricted. Please make PRs to the 'develop' branch."
            exit 1
          fi
